### PR TITLE
add cache-control header... maybe

### PR DESCRIPTION
**Pull request by GvandeSteeg**

### CODE REVIEW

**Review by HarryHung — CHANGES_REQUESTED** [review]
I am not familiar with PHP, I assume this alter the Cache Control behaviour of the PHP server?

Do you want this line to be part of the HTML when the webpage is loaded? In CRA React app `src/index.html` is ignored, the actual HTML being loaded is `public/index.html`. So you will need to add this line to `public/index.html`, and it will become part of the built website. 

For example the analytic Javascript is added this way: https://github.com/sanger-pathogens/bentley-app/blob/11fdfb7e223c5fe1f4d4cf9bec7f2a033e9153b4/public/index.html#L46

**Comment by GvandeSteeg** [comment]
> I am not familiar with PHP, I assume this alter the Cache Control behaviour of the PHP server?
> 
> Do you want this line to be part of the HTML when the webpage is loaded? In CRA React app `src/index.html` is ignored, the actual HTML being loaded is `public/index.html`. So you will need to add this line to `public/index.html`, and it will become part of the built website.
> 
> For example the analytic Javascript is added this way:
> 
> https://github.com/sanger-pathogens/bentley-app/blob/11fdfb7e223c5fe1f4d4cf9bec7f2a033e9153b4/public/index.html#L46

ah cool, thanks Harry. I'll admit I had no idea what to do, just followed some SO thread. I'll put them in public instead. The issue is we still won't know if this will work, nor can we really test it working.

> Even though we're many versions of Chrome later, this answer still fixed a problem we were having in development. Also, just to clarify, this header can be added in any web server - it's not PHP specific. – 
[Randall](https://stackoverflow.com/users/584940/randall)
 [CommentedSep 28, 2018 at 16:31](https://stackoverflow.com/questions/26111389/chrome-keeps-loading-a-old-cache-of-my-website/36646558#comment92057424_36646558)

**Review by HarryHung — APPROVED** [review]
Screenshot 2024-11-06 at 12 20 08

I can confirm the PHP code is inserted to the web app now.

**Comment by HarryHung** [comment]
> > I am not familiar with PHP, I assume this alter the Cache Control behaviour of the PHP server?
> > Do you want this line to be part of the HTML when the webpage is loaded? In CRA React app `src/index.html` is ignored, the actual HTML being loaded is `public/index.html`. So you will need to add this line to `public/index.html`, and it will become part of the built website.
> > For example the analytic Javascript is added this way:
> > https://github.com/sanger-pathogens/bentley-app/blob/11fdfb7e223c5fe1f4d4cf9bec7f2a033e9153b4/public/index.html#L46
> 
> ah cool, thanks Harry. I'll admit I had no idea what to do, just followed some SO thread. I'll put them in public instead. The issue is we still won't know if this will work, nor can we really test it working.
> 
> > Even though we're many versions of Chrome later, this answer still fixed a problem we were having in development. Also, just to clarify, this header can be added in any web server - it's not PHP specific. –
> > [Randall](https://stackoverflow.com/users/584940/randall)
> > [CommentedSep 28, 2018 at 16:31](https://stackoverflow.com/questions/26111389/chrome-keeps-loading-a-old-cache-of-my-website/36646558#comment92057424_36646558)

No worries, I got you. 

The worst case scenario is just doing nothing, so I think we shall proceed anyway. 

As stated in the linked thread, it seems to be a Chrome-specific issue? Because I use Firefox personally and never notice this behaviour. 

If you are happy, I will merge the PR, release, and deploy.

**Comment by GvandeSteeg** [comment]
yes please!

**Pull request merged**
